### ISSUE TITLE
gatsby-transformer-inline-svg now supports file system

### ISSUE THREAD

**Issue by axe312ger** [hazem3500/gatsby-transformer-inline-svg-v2#2]
Hey!

I finally added gatsby-source-filesystem support to [gatsby-transformer-inline-svg](https://github.com/axe312ger/gatsby-transformer-inline-svg/releases/tag/v1.1.0)

You might want to deprecate your variant :)

Best,
Benedikt

**Comment by hazem3500** [comment]
Awesome 🚀, will deprecate package 👍
